name: doctest
on:
  push:
    branches: ['*']
jobs:
  build:
    runs-on: ubuntu-latest  # VM to run your workflow

    env:
      # Load your GitHub secret into an environment variable
      GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}

    steps:
        - uses: actions/checkout@v2
        - name: Set up Python ${{matrix.python}}
          uses: actions/setup-python@v2
          with:
            python-version: ${{matrix.python}}
        - name: Install dependencies
          run: | 
            pip install requests
            pip install -r requirements.txt
        - name: Run tests
          run: |
            python -m doctest --verbose chat.py
            # no coverage reports anywhere?
