name: integration_test
on:
  push:
    branches: ['*']
jobs:
  build:
    runs-on: ubuntu-latest  # VM to run your workflow

    env:
      # Load your GitHub secret into an environment variable
      GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}

    steps:
        - uses: actions/checkout@v3
        - name: Setup Python
          uses: actions/setup-python@v4
          with:
            python-version: '3.10'
        - run: pip install .
        - run: pip install pytest
        - run: pytest tests/test_integration.py